"""The timeline document: what the editor edits and the compiler reads.

The whole director state is one JSON object stored in a single node widget. Keeping it
a plain document -- rather than state scattered across widgets -- means a timeline can
be copied between graphs, diffed in review, and generated by a script.

Frames, not seconds, are authoritative. Seconds are a presentation detail derived at
compile time, so a timeline never drifts by a rounding error.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field, replace
from typing import Any, Iterable, Literal

from . import lattice

RefKind = Literal["picture", "audio", "video"]

ROLE_TASKS: dict[str, str] = {
    "reference": "reference generation",
    "first frame": "keyframe completion",
    "keyframe": "keyframe completion",
    "last frame": "keyframe completion",
    "continue from": "video continuation",
    "edit": "video editing",
}
"""What an attached file is *for*, and the task type the guide gives that job.

The guide asks the summary to name every relationship the prompt has, combined with ` + `.
Which one applies is not something a file can be inspected for -- the same photograph is a
style reference or a literal first frame depending on what the author meant -- so the role
is authored, and only the mapping to the guide's vocabulary lives here.

`reference` is the default and the honest one: guidance, not a concrete frame anchor."""

ROLES: tuple[str, ...] = tuple(ROLE_TASKS)

FRAME_ROLES = ("first frame", "keyframe", "last frame")
"""Roles that make a picture a concrete frame of the target video.

`retention_analysis` names these where it would otherwise say "appears in": the guide
writes `<Picture 2> ([Shot 1] first frame): fully_preserved - ...`."""

REFERENCE_DIALECT = "reference"
"""The six-section shape H3 wants when anything is attached.

Not an author's choice, which is why it is not in `DIALECTS`. Attaching a file routes the
graph to `MiniMaxH3ReferenceToVideo` (`nodes/director.py`), and full-reference mode has
its own prompt format: `subject_definitions`, `summary`, `retention_analysis`,
`detailed_description`, `overall_soundscape`, `non_diegetic_music`, in that order
(`skills/h3-prompt-writing/references/ref-en.txt` in MiniMax's own repo). Letting a combo
box disagree with the node that receives the prompt is how the two silently drift apart,
so the compiler reads the attachments instead of asking."""

RETENTIONS = ("fully_preserved", "partially_preserved", "attribute_transfer", "weak_reference")
"""How much of a reference survives into the target video, for `retention_analysis`.

Fixed English values in the output format, not prose: the guide lists exactly these four
for visible content. Audio has its own set, which this project does not emit yet."""

CAMERA_PROSE: dict[str, str] = {
    "static": "The camera holds a static shot.",
    "dolly_in": "The camera pushes in with small amplitude at slow speed.",
    "dolly_out": "The camera pulls out with small amplitude at slow speed.",
    "pan_left": "The camera pans left.",
    "pan_right": "The camera pans right.",
    "tilt_up": "The camera tilts up.",
    "tilt_down": "The camera tilts down.",
    "orbit": "The camera moves in an arc around the subject.",
    "handheld": "The camera shakes slightly.",
    "crash_zoom": "The camera zooms in with large amplitude at fast speed.",
}
"""Camera verbs the editor offers, and the sentence each one contributes.

H3 reads prose, not enum values, so the mapping lives here rather than in the model.
Unknown keys pass through untouched -- a director should never be blocked by a
vocabulary this file happens not to know yet.
"""


@dataclass(frozen=True, slots=True)
class Reference:
    """One wired input, addressable from prose as `<Picture 1>`, `<Audio 2>`, ...

    `index` is 1-based to match the token the model reads, so what a user types and
    what the graph wires up are the same number.
    """

    kind: RefKind
    index: int
    label: str = ""

    @property
    def token(self) -> str:
        return f"<{self.kind.capitalize()} {self.index}>"


def _lines(data: Any) -> tuple["Line", ...]:
    """Read the dialogue on a shot. Anything unreadable is dropped, never guessed at."""
    if not isinstance(data, list):
        return ()
    return tuple(
        Line(
            text=str(item.get("text", "")),
            speaker=str(item.get("speaker", "")),
            ids=str(item.get("ids", "S1")),
            delivery=str(item.get("delivery", "says")),
            language=str(item.get("language", "English")),
        )
        for item in data
        if isinstance(item, dict) and str(item.get("text", "")).strip()
    )


def _sentences(parts: Iterable[str]) -> str:
    """Join fragments into prose, adding the full stops the author left out.

    A shot is written as several pieces -- what happens, how it is filmed, who speaks --
    and they arrive as separate fields. Run together they become one unreadable sentence;
    given a blind `". "` they collect double punctuation after anything already ended.
    """
    out = ""
    for part in parts:
        piece = part.strip()
        if not piece:
            continue
        if not out:
            out = piece
            continue
        separator = " " if out.endswith((".", "!", "?", ",")) else ". "
        out = f"{out}{separator}{piece}"
    return out


@dataclass(frozen=True, slots=True)
class Line:
    """One spoken line, in the exact shape H3's guide asks for.

    The split is the whole point. Everything about *who* is speaking -- their description,
    their ID, how they deliver it -- goes outside `<d>`; inside it goes a language tag and
    the words themselves, verbatim. The guide is explicit that the words must not be
    translated or rewritten, which is a rule about our formatting as much as the model's.
    """

    text: str
    """What is actually said. Never touched: punctuation and language are the author's."""
    speaker: str = ""
    """Who says it, and how they sound -- age, gender, pitch, timbre, accent, on-screen or
    not. The guide asks for enough to fix an identity the first time a speaker appears."""
    ids: str = "S1"
    """`S1`, or `S1,S2` for a group speaking together."""
    delivery: str = "says"
    """The verb: says, shouts, whispers, mutters."""
    language: str = "English"
    """The `[English]` tag inside `<d>`. The words keep their own language; this names it."""

    def render(self) -> str:
        """`The woman (S1) says: <d>[English] ...</d>`"""
        said = self.text.strip()
        if not said:
            return ""
        who = " ".join(part for part in (self.speaker.strip(), f"({self.ids.strip() or 'S1'})") if part)
        verb = self.delivery.strip() or "says"
        tag = self.language.strip() or "English"
        return f"{who} {verb}: <d>[{tag}] {said}</d>"


@dataclass(frozen=True, slots=True)
class Shot:
    """A contiguous run of frames with one description."""

    start: int
    length: int
    prompt: str
    camera: str = ""
    """Legacy. The editor no longer offers this on a shot -- camera work belongs on the
    CAMERA track, where a move is free to straddle a cut. Documents written before that
    still carry it, and are still compiled with the sentence appended to the shot's line,
    so an old graph keeps producing the prompt it always did."""
    media: dict | None = None
    """An attached file: `{"kind": "image", "filename": ..., "subfolder": ...}`."""
    lines: tuple[Line, ...] = ()
    """What is spoken during this shot, in order."""

    @property
    def end(self) -> int:
        return self.start + self.length

    def text(self) -> str:
        """Prompt, the camera sentence, then the dialogue -- in that order.

        Dialogue comes last because the guide describes a shot as composition, action and
        camera first, with speech landing inside the scene that was just established.
        """
        prose = CAMERA_PROSE.get(self.camera, self.camera).strip()
        parts = [self.prompt.strip(), prose]
        parts.extend(line.render() for line in self.lines)
        return _sentences(part for part in parts if part)


@dataclass(frozen=True, slots=True)
class Cue:
    """A span on the audio track: dialogue, a sound event, a music direction."""

    start: int
    length: int
    prompt: str
    media: dict | None = None

    @property
    def end(self) -> int:
        return self.start + self.length


@dataclass(frozen=True, slots=True)
class Move:
    """A span on the camera track.

    Camera work is separate from the shot it happens in: a push-in can start midway
    through a shot, and two moves can share one description of the scene. Keeping it on
    its own track is also what makes it editable as a track rather than a dropdown.
    """

    start: int
    length: int
    camera: str = ""
    prompt: str = ""

    @property
    def end(self) -> int:
        return self.start + self.length

    def text(self) -> str:
        prose = CAMERA_PROSE.get(self.camera, self.camera).strip()
        body = self.prompt.strip()
        if prose and body:
            return f"{prose} {body}"
        return prose or body


@dataclass(slots=True)
class Timeline:
    """The whole document."""

    global_prompt: str = ""
    shots: list[Shot] = field(default_factory=list)
    cues: list[Cue] = field(default_factory=list)
    moves: list[Move] = field(default_factory=list)
    references: list[Reference] = field(default_factory=list)
    music: str = ""
    """`non_diegetic_music`: score only the audience hears. Empty compiles to `N/A`.

    The model's guide separates this from everything the characters can hear, and asks
    for instrumentation, tempo and dynamics rather than mood words."""
    fps: int = lattice.FPS
    duration: int = 0
    """Explicit clip length in frames. Zero means "as long as the content needs"."""

    # -- derived -----------------------------------------------------------

    @property
    def span(self) -> int:
        """Last frame covered by any track. Zero for an empty timeline."""
        ends = [item.end for item in (*self.shots, *self.cues, *self.moves)]
        return max(ends, default=0)

    @property
    def length(self) -> int:
        """The clip length H3 will be asked for.

        An explicit duration wins; otherwise the content decides. Either way it lands on
        the 17-frame lattice, which is why it can sit slightly past the last shot.
        """
        return lattice.snap_up(self.duration or self.span)

    def ordered_shots(self) -> list[Shot]:
        return sorted(self.shots, key=lambda shot: (shot.start, shot.length))

    def ordered_cues(self) -> list[Cue]:
        return sorted(self.cues, key=lambda cue: (cue.start, cue.length))

    def ordered_moves(self) -> list[Move]:
        return sorted(self.moves, key=lambda move: (move.start, move.length))

    def refs_of(self, kind: RefKind) -> list[Reference]:
        return sorted(
            (ref for ref in self.references if ref.kind == kind),
            key=lambda ref: ref.index,
        )

    def prose(self) -> Iterable[str]:
        """Every piece of author-written text, for linting."""
        yield self.global_prompt
        for shot in self.shots:
            yield shot.prompt
        for cue in self.cues:
            yield cue.prompt
        for move in self.moves:
            yield move.prompt
        for shot in self.shots:
            for line in shot.lines:
                yield line.speaker

    # -- serialisation -----------------------------------------------------

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "Timeline":
        return cls(
            global_prompt=str(data.get("global_prompt", "")),
            music=str(data.get("music", "")),
            shots=[
                Shot(
                    start=int(item.get("start", 0)),
                    length=int(item.get("length", 0)),
                    prompt=str(item.get("prompt", "")),
                    camera=str(item.get("camera", "")),
                    media=item.get("media") or None,
                    lines=_lines(item.get("lines")),
                )
                for item in data.get("shots", [])
            ],
            cues=[
                Cue(
                    start=int(item.get("start", 0)),
                    length=int(item.get("length", 0)),
                    prompt=str(item.get("prompt", "")),
                    media=item.get("media") or None,
                )
                for item in data.get("cues", [])
            ],
            moves=[
                Move(
                    start=int(item.get("start", 0)),
                    length=int(item.get("length", 0)),
                    camera=str(item.get("camera", "")),
                    prompt=str(item.get("prompt", "")),
                )
                for item in data.get("moves", [])
            ],
            references=[
                Reference(
                    kind=str(item.get("kind", "picture")),  # type: ignore[arg-type]
                    index=int(item.get("index", 1)),
                    label=str(item.get("label", "")),
                )
                for item in data.get("references", [])
            ],
            duration=int(data.get("duration", 0)),
            fps=int(data.get("fps", lattice.FPS)),
        )

    @classmethod
    def from_json(cls, text: str) -> "Timeline":
        """Parse a widget payload. An empty or blank widget is an empty timeline."""
        text = (text or "").strip()
        if not text:
            return cls()
        return cls.from_dict(json.loads(text))

    def to_dict(self) -> dict[str, Any]:
        return {
            "version": 1,
            "fps": self.fps,
            "duration": self.duration,
            "global_prompt": self.global_prompt,
            "music": self.music,
            "shots": [
                {
                    "start": shot.start,
                    "length": shot.length,
                    "prompt": shot.prompt,
                    "camera": shot.camera,
                    **({"media": shot.media} if shot.media else {}),
                    **({"lines": [
                        {
                            "text": line.text,
                            "speaker": line.speaker,
                            "ids": line.ids,
                            "delivery": line.delivery,
                            "language": line.language,
                        }
                        for line in shot.lines
                    ]} if shot.lines else {}),
                }
                for shot in self.shots
            ],
            "cues": [
                {
                    "start": cue.start,
                    "length": cue.length,
                    "prompt": cue.prompt,
                    **({"media": cue.media} if cue.media else {}),
                }
                for cue in self.cues
            ],
            "moves": [
                {
                    "start": move.start,
                    "length": move.length,
                    "camera": move.camera,
                    "prompt": move.prompt,
                }
                for move in self.moves
            ],
            "references": [
                {"kind": ref.kind, "index": ref.index, "label": ref.label}
                for ref in self.references
            ],
        }

    def to_json(self, indent: int | None = None) -> str:
        return json.dumps(self.to_dict(), indent=indent, ensure_ascii=False)

    # -- editing -----------------------------------------------------------

    def with_references(self, references: list[Reference]) -> "Timeline":
        """A copy whose wired inputs are `references`.

        The node calls this so the linter compares prose against what is actually
        connected, not against what the editor last remembered.
        """
        return replace(self, references=list(references))
