"""The timeline document: what the editor edits and the compiler reads.

The whole director state is one JSON object stored in a single node widget. Keeping it
a plain document -- rather than state scattered across widgets -- means a timeline can
be copied between graphs, diffed in review, and generated by a script.

Frames, not seconds, are authoritative. Seconds are a presentation detail derived at
compile time, so a timeline never drifts by a rounding error.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field, replace
from typing import Any, Iterable, Literal

from . import lattice

RefKind = Literal["picture", "audio", "video"]

DIALECTS = ("timeline", "shots")
"""How the shot list is rendered. Both appear in the official H3 templates:
`timeline` emits `[0s-1s] ...` lines, `shots` emits `SHOT 1: ...` lines."""

CAMERA_PROSE: dict[str, str] = {
    "static": "The camera holds still.",
    "dolly_in": "The camera dollies slowly in.",
    "dolly_out": "The camera pulls slowly back.",
    "pan_left": "The camera pans left.",
    "pan_right": "The camera pans right.",
    "tilt_up": "The camera tilts up.",
    "tilt_down": "The camera tilts down.",
    "orbit": "The camera orbits the subject.",
    "handheld": "Loose handheld movement.",
    "crash_zoom": "A fast crash zoom snaps in.",
}
"""Camera verbs the editor offers, and the sentence each one contributes.

H3 reads prose, not enum values, so the mapping lives here rather than in the model.
Unknown keys pass through untouched -- a director should never be blocked by a
vocabulary this file happens not to know yet.
"""


@dataclass(frozen=True, slots=True)
class Reference:
    """One wired input, addressable from prose as `<Picture 1>`, `<Audio 2>`, ...

    `index` is 1-based to match the token the model reads, so what a user types and
    what the graph wires up are the same number.
    """

    kind: RefKind
    index: int
    label: str = ""

    @property
    def token(self) -> str:
        return f"<{self.kind.capitalize()} {self.index}>"


@dataclass(frozen=True, slots=True)
class Shot:
    """A contiguous run of frames with one description."""

    start: int
    length: int
    prompt: str
    camera: str = ""
    media: dict | None = None
    """An attached file: `{"kind": "image", "filename": ..., "subfolder": ...}`."""

    @property
    def end(self) -> int:
        return self.start + self.length

    def text(self) -> str:
        """Prompt plus the camera sentence, if any."""
        prose = CAMERA_PROSE.get(self.camera, self.camera).strip()
        body = self.prompt.strip()
        if not prose:
            return body
        if not body:
            return prose
        separator = " " if body.endswith((".", "!", "?", ",")) else ". "
        return f"{body}{separator}{prose}"


@dataclass(frozen=True, slots=True)
class Cue:
    """A span on the audio track: dialogue, a sound event, a music direction."""

    start: int
    length: int
    prompt: str
    media: dict | None = None

    @property
    def end(self) -> int:
        return self.start + self.length


@dataclass(frozen=True, slots=True)
class Move:
    """A span on the camera track.

    Camera work is separate from the shot it happens in: a push-in can start midway
    through a shot, and two moves can share one description of the scene. Keeping it on
    its own track is also what makes it editable as a track rather than a dropdown.
    """

    start: int
    length: int
    camera: str = ""
    prompt: str = ""

    @property
    def end(self) -> int:
        return self.start + self.length

    def text(self) -> str:
        prose = CAMERA_PROSE.get(self.camera, self.camera).strip()
        body = self.prompt.strip()
        if prose and body:
            return f"{prose} {body}"
        return prose or body


@dataclass(slots=True)
class Timeline:
    """The whole document."""

    global_prompt: str = ""
    shots: list[Shot] = field(default_factory=list)
    cues: list[Cue] = field(default_factory=list)
    moves: list[Move] = field(default_factory=list)
    references: list[Reference] = field(default_factory=list)
    dialect: str = "timeline"
    fps: int = lattice.FPS
    duration: int = 0
    """Explicit clip length in frames. Zero means "as long as the content needs"."""

    # -- derived -----------------------------------------------------------

    @property
    def span(self) -> int:
        """Last frame covered by any track. Zero for an empty timeline."""
        ends = [item.end for item in (*self.shots, *self.cues, *self.moves)]
        return max(ends, default=0)

    @property
    def length(self) -> int:
        """The clip length H3 will be asked for.

        An explicit duration wins; otherwise the content decides. Either way it lands on
        the 17-frame lattice, which is why it can sit slightly past the last shot.
        """
        return lattice.snap_up(self.duration or self.span)

    def ordered_shots(self) -> list[Shot]:
        return sorted(self.shots, key=lambda shot: (shot.start, shot.length))

    def ordered_cues(self) -> list[Cue]:
        return sorted(self.cues, key=lambda cue: (cue.start, cue.length))

    def ordered_moves(self) -> list[Move]:
        return sorted(self.moves, key=lambda move: (move.start, move.length))

    def refs_of(self, kind: RefKind) -> list[Reference]:
        return sorted(
            (ref for ref in self.references if ref.kind == kind),
            key=lambda ref: ref.index,
        )

    def prose(self) -> Iterable[str]:
        """Every piece of author-written text, for linting."""
        yield self.global_prompt
        for shot in self.shots:
            yield shot.prompt
        for cue in self.cues:
            yield cue.prompt
        for move in self.moves:
            yield move.prompt

    # -- serialisation -----------------------------------------------------

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "Timeline":
        return cls(
            global_prompt=str(data.get("global_prompt", "")),
            shots=[
                Shot(
                    start=int(item.get("start", 0)),
                    length=int(item.get("length", 0)),
                    prompt=str(item.get("prompt", "")),
                    camera=str(item.get("camera", "")),
                    media=item.get("media") or None,
                )
                for item in data.get("shots", [])
            ],
            cues=[
                Cue(
                    start=int(item.get("start", 0)),
                    length=int(item.get("length", 0)),
                    prompt=str(item.get("prompt", "")),
                    media=item.get("media") or None,
                )
                for item in data.get("cues", [])
            ],
            moves=[
                Move(
                    start=int(item.get("start", 0)),
                    length=int(item.get("length", 0)),
                    camera=str(item.get("camera", "")),
                    prompt=str(item.get("prompt", "")),
                )
                for item in data.get("moves", [])
            ],
            references=[
                Reference(
                    kind=str(item.get("kind", "picture")),  # type: ignore[arg-type]
                    index=int(item.get("index", 1)),
                    label=str(item.get("label", "")),
                )
                for item in data.get("references", [])
            ],
            dialect=str(data.get("dialect", "timeline")),
            duration=int(data.get("duration", 0)),
            fps=int(data.get("fps", lattice.FPS)),
        )

    @classmethod
    def from_json(cls, text: str) -> "Timeline":
        """Parse a widget payload. An empty or blank widget is an empty timeline."""
        text = (text or "").strip()
        if not text:
            return cls()
        return cls.from_dict(json.loads(text))

    def to_dict(self) -> dict[str, Any]:
        return {
            "version": 1,
            "fps": self.fps,
            "dialect": self.dialect,
            "duration": self.duration,
            "global_prompt": self.global_prompt,
            "shots": [
                {
                    "start": shot.start,
                    "length": shot.length,
                    "prompt": shot.prompt,
                    "camera": shot.camera,
                    **({"media": shot.media} if shot.media else {}),
                }
                for shot in self.shots
            ],
            "cues": [
                {
                    "start": cue.start,
                    "length": cue.length,
                    "prompt": cue.prompt,
                    **({"media": cue.media} if cue.media else {}),
                }
                for cue in self.cues
            ],
            "moves": [
                {
                    "start": move.start,
                    "length": move.length,
                    "camera": move.camera,
                    "prompt": move.prompt,
                }
                for move in self.moves
            ],
            "references": [
                {"kind": ref.kind, "index": ref.index, "label": ref.label}
                for ref in self.references
            ],
        }

    def to_json(self, indent: int | None = None) -> str:
        return json.dumps(self.to_dict(), indent=indent, ensure_ascii=False)

    # -- editing -----------------------------------------------------------

    def with_references(self, references: list[Reference]) -> "Timeline":
        """A copy whose wired inputs are `references`.

        The node calls this so the linter compares prose against what is actually
        connected, not against what the editor last remembered.
        """
        return replace(self, references=list(references))
